os:
  - linux
  - osx

compiler: gcc
language: c
sudo: require
dist: bionic

install:
  - if [ $TRAVIS_OS_NAME == osx ]; then
        HOMEBREW_NO_AUTO_UPDATE=1 brew install cmocka;
        HOMEBREW_NO_AUTO_UPDATE=1 brew cask install oclint;
    else
        sudo apt-get install -y libcmocka-dev;
    fi

script:
  - mkdir build && cd build
  - cmake .. -DBUILD_TESTS=on && make && make test
  - cd -
  - if [ $TRAVIS_OS_NAME == osx ]; then
        oclint-json-compilation-database -e 'test_.*' -p build;
    fi
